import Link from "next/link";
import type { ButtonHTMLAttributes,InputHTMLAttributes,SelectHTMLAttributes,TextareaHTMLAttributes } from "react";
import { useId } from "react";

export function Button({className="",variant="primary",...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"ghost"|"danger"}){const variants={primary:"bg-primary text-[#fffaf0] border-primary hover:bg-[#3a332a]",secondary:"bg-surface text-primary border-line hover:border-[#b9aa95] hover:bg-[#f7f2ea]",ghost:"bg-transparent text-primary border-transparent hover:bg-[#ece6dc]",danger:"bg-[#8d3d34] text-white border-[#8d3d34] hover:bg-[#763129]"};return <button className={`inline-flex min-h-10 items-center justify-center gap-2 rounded-[.35rem] border px-4 py-2 text-[.78rem] font-semibold tracking-[.01em] transition disabled:cursor-not-allowed disabled:opacity-45 ${variants[variant]} ${className}`} {...props}/>}
export function ButtonLink({href,children,variant="primary",className=""}:{href:string;children:React.ReactNode;variant?:"primary"|"secondary"|"ghost";className?:string}){const variants={primary:"bg-[#7a3e32] text-white border-[#7a3e32] hover:bg-[#603027]",secondary:"bg-surface text-primary border-line hover:border-[#b9aa95]",ghost:"text-primary border-transparent hover:bg-[#ece6dc]"};return <Link href={href} className={`inline-flex min-h-10 items-center justify-center rounded-[.35rem] border px-4 py-2 text-[.78rem] font-semibold tracking-[.01em] transition ${variants[variant]} ${className}`}>{children}</Link>}
export function Input({label,error,help,className="","aria-describedby":callerDescribedBy,"aria-invalid":callerInvalid,...props}:InputHTMLAttributes<HTMLInputElement>&{label?:string;error?:string;help?:string}){const descriptionId=useId();const errorId=`${descriptionId}-error`;const helpId=`${descriptionId}-help`;const describedBy=[callerDescribedBy,error&&errorId,help&&helpId].filter(Boolean).join(" ")||undefined;return <div className="block"><label>{label&&<span className="label">{label}</span>}<input className={`control ${className}`} aria-describedby={describedBy} aria-invalid={error?true:callerInvalid} {...props}/></label>{error&&<span id={errorId} className="field-error">{error}</span>}{help&&<span id={helpId} className="help">{help}</span>}</div>}
export function Textarea({label,error,help,className="","aria-describedby":callerDescribedBy,"aria-invalid":callerInvalid,...props}:TextareaHTMLAttributes<HTMLTextAreaElement>&{label?:string;error?:string;help?:string}){const descriptionId=useId();const errorId=`${descriptionId}-error`;const helpId=`${descriptionId}-help`;const describedBy=[callerDescribedBy,error&&errorId,help&&helpId].filter(Boolean).join(" ")||undefined;return <div className="block"><label>{label&&<span className="label">{label}</span>}<textarea className={`control min-h-28 resize-y ${className}`} aria-describedby={describedBy} aria-invalid={error?true:callerInvalid} {...props}/></label>{error&&<span id={errorId} className="field-error">{error}</span>}{help&&<span id={helpId} className="help">{help}</span>}</div>}
export function Select({label,options,...props}:SelectHTMLAttributes<HTMLSelectElement>&{label?:string;options:{value:string;label:string}[]}){return <div className="block"><label>{label&&<span className="label">{label}</span>}<select className="control" {...props}>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label></div>}
export function Badge({children,tone="neutral"}:{children:React.ReactNode;tone?:"neutral"|"good"|"warn"|"info"}){const tones={neutral:"bg-[#eee9df] text-[#625c53] border-[#ddd4c6]",good:"bg-[#e7ede2] text-[#4b6145] border-[#ced9c8]",warn:"bg-[#f2e7d5] text-[#7c5e2d] border-[#e1d1b8]",info:"bg-[#e9e6df] text-primary border-[#d6cec0]"};return <span className={`inline-flex rounded-full border px-2.5 py-1 text-[.66rem] font-semibold tracking-wide ${tones[tone]}`}>{children}</span>}
export function PageHeader({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:React.ReactNode}){return <header className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div>{eyebrow&&<p className="eyebrow mb-3">{eyebrow}</p>}<h1 className="editorial-title text-4xl sm:text-5xl">{title}</h1>{description&&<p className="mt-3 max-w-2xl text-sm leading-6 text-muted">{description}</p>}</div>{actions&&<div className="flex shrink-0 flex-wrap gap-2">{actions}</div>}</header>}
export function Breadcrumb({items}:{items:{label:string;href?:string}[]}){return <nav aria-label="Breadcrumb" className="mb-5 flex flex-wrap items-center gap-2 text-[.7rem] text-muted">{items.map((item,index)=><span key={`${item.label}-${index}`} className="flex items-center gap-2">{index>0&&<span aria-hidden className="text-[#b5aa9a]">/</span>}{item.href?<Link className="hover:text-accent" href={item.href}>{item.label}</Link>:<span aria-current="page">{item.label}</span>}</span>)}</nav>}
export function Empty({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="surface flex min-h-52 flex-col items-center justify-center px-6 py-10 text-center"><div className="mb-5 flex h-10 w-10 items-center justify-center rounded-full border border-[#cdbb9f] font-serif text-accent">✦</div><h3 className="editorial-title text-2xl">{title}</h3><p className="mt-3 max-w-md text-sm leading-6 text-muted">{description}</p>{action&&<div className="mt-6">{action}</div>}</div>}
export function Skeleton({className="h-5 w-full"}:{className?:string}){return <div aria-hidden className={`animate-pulse rounded bg-[#e5ded2] ${className}`}/>}
export function LoadingBlock(){return <div role="status" aria-live="polite" aria-label="Memuat konten" className="space-y-4"><Skeleton className="h-9 w-56"/><Skeleton className="h-32 w-full"/><Skeleton className="h-48 w-full"/></div>}
export function ResponsiveTable({headers,children}:{headers:string[];children:React.ReactNode}){return <div className="table-wrap"><table className="responsive-table"><thead><tr>{headers.map(header=><th key={header} scope="col">{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
export function Pagination({page,pages,onPage}:{page:number;pages:number;onPage:(page:number)=>void}){if(pages<=1)return null;return <div className="mt-5 flex items-center justify-between text-sm"><Button variant="secondary" disabled={page<=1} onClick={()=>onPage(page-1)}>Sebelumnya</Button><span className="text-muted">Halaman {page} dari {pages}</span><Button variant="secondary" disabled={page>=pages} onClick={()=>onPage(page+1)}>Berikutnya</Button></div>}
