"use client";
import { FormEvent, useState } from "react";
import { api } from "@/lib/api";
import { Breadcrumb, Button, Input, PageHeader, Select, Textarea } from "@/components/ui";
import { useToast } from "@/components/ui/toast";

export type GeneratorKind="slides"|"module"|"quiz"|"assignment"|"lesson-plan";
type Field={name:string;label:string;type?:"text"|"number"|"textarea"|"select"|"checkbox";placeholder?:string;help?:string;required?:boolean;default?:string|number|boolean;options?:{value:string;label:string}[];min?:number;max?:number};
const commonLanguage={name:"language",label:"Bahasa keluaran",type:"select" as const,default:"id",options:[{value:"id",label:"Bahasa Indonesia"},{value:"en",label:"English"}]};
const configs:Record<GeneratorKind,{title:string;description:string;fields:Field[]}>= {
 slides:{title:"Presentation Slides",description:"Susun alur presentasi akademik dari topik dan kebutuhan audiens.",fields:[{name:"topic",label:"Topik presentasi",required:true,placeholder:"Contoh: Etika penggunaan AI"},{name:"audience",label:"Audiens",required:true,placeholder:"Mahasiswa tahun pertama"},{name:"slide_count",label:"Jumlah slide",type:"number",default:10,min:3,max:50},{name:"tone",label:"Gaya penyampaian",type:"select",default:"academic",options:[{value:"academic",label:"Akademik"},{value:"professional",label:"Profesional"},{value:"conversational",label:"Interaktif"}]},{name:"key_points",label:"Poin yang wajib dibahas",type:"textarea",placeholder:"Satu poin per baris"},commonLanguage]},
 module:{title:"Learning Module",description:"Rancang struktur modul mandiri yang terukur dan mudah diikuti.",fields:[{name:"title",label:"Judul modul",required:true,placeholder:"Dasar-dasar Analitik Data"},{name:"topic",label:"Cakupan topik",type:"textarea",required:true},{name:"audience",label:"Target pembelajar",required:true},{name:"learning_objectives",label:"Tujuan pembelajaran",type:"textarea",required:true},{name:"duration_hours",label:"Estimasi durasi (jam)",type:"number",default:2,min:1,max:80},{name:"difficulty",label:"Tingkat kesulitan",type:"select",default:"beginner",options:[{value:"beginner",label:"Pemula"},{value:"intermediate",label:"Menengah"},{value:"advanced",label:"Lanjutan"}]},{name:"format",label:"Format",type:"select",default:"self_paced",options:[{value:"self_paced",label:"Belajar mandiri"},{value:"facilitated",label:"Dengan fasilitator"},{value:"blended",label:"Blended"}]},commonLanguage]},
 quiz:{title:"Quiz Generator",description:"Siapkan rancangan pertanyaan sesuai konteks dan tingkat kesulitan.",fields:[{name:"topic",label:"Topik kuis",required:true},{name:"audience",label:"Audiens",required:true},{name:"question_count",label:"Jumlah pertanyaan",type:"number",default:10,min:1,max:100},{name:"question_types",label:"Tipe pertanyaan",type:"select",default:"mixed",options:[{value:"multiple_choice",label:"Pilihan ganda"},{value:"true_false",label:"Benar / salah"},{value:"short_answer",label:"Jawaban singkat"},{value:"mixed",label:"Campuran"}]},{name:"difficulty",label:"Kesulitan",type:"select",default:"medium",options:[{value:"easy",label:"Mudah"},{value:"medium",label:"Sedang"},{value:"hard",label:"Sulit"}]},{name:"include_answers",label:"Sertakan kunci jawaban",type:"checkbox",default:true},commonLanguage]},
 assignment:{title:"Assignment Generator",description:"Rancang tugas yang selaras dengan tujuan dan konteks pembelajaran.",fields:[{name:"course",label:"Mata kuliah / program",required:true},{name:"topic",label:"Topik tugas",required:true},{name:"audience",label:"Audiens",required:true},{name:"assignment_type",label:"Jenis tugas",type:"select",default:"individual",options:[{value:"individual",label:"Individu"},{value:"group",label:"Kelompok"},{value:"project",label:"Proyek"},{value:"case_study",label:"Studi kasus"}]},{name:"difficulty",label:"Kesulitan",type:"select",default:"medium",options:[{value:"easy",label:"Mudah"},{value:"medium",label:"Sedang"},{value:"hard",label:"Sulit"}]},{name:"due_days",label:"Waktu pengerjaan (hari)",type:"number",default:7,min:1,max:180},{name:"objectives",label:"Tujuan penugasan",type:"textarea",required:true},{name:"constraints",label:"Ketentuan dan batasan",type:"textarea"},commonLanguage]},
 "lesson-plan":{title:"Lesson Plan",description:"Bangun alur pengajaran lengkap dari pembukaan hingga asesmen.",fields:[{name:"subject",label:"Mata pelajaran / mata kuliah",required:true},{name:"topic",label:"Topik",required:true},{name:"grade_level",label:"Tingkat / jenjang",required:true,placeholder:"SMA kelas 11 / Semester 2"},{name:"duration_minutes",label:"Durasi (menit)",type:"number",default:90,min:15,max:480},{name:"learning_objectives",label:"Tujuan pembelajaran",type:"textarea",required:true},{name:"teaching_method",label:"Metode",type:"select",default:"active_learning",options:[{value:"active_learning",label:"Active learning"},{value:"lecture",label:"Ceramah interaktif"},{value:"project_based",label:"Project-based"},{value:"discussion",label:"Diskusi"}]},{name:"assessment_strategy",label:"Strategi asesmen",type:"textarea"},{name:"resources",label:"Sumber dan alat",type:"textarea"},commonLanguage]}
};
export function GeneratorForm({kind,slug}:{kind:GeneratorKind;slug:string}){const config=configs[kind];const initial=Object.fromEntries(config.fields.map(field=>[field.name,field.default??(field.type==="checkbox"?false:"")]));const [form,setForm]=useState<Record<string,string|number|boolean>>(initial);const [busy,setBusy]=useState(false);const {show}=useToast();async function submit(event:FormEvent){event.preventDefault();setBusy(true);try{await api(`/generation/${kind}`,{method:"POST",body:JSON.stringify(form)});}catch{/* The current API contract intentionally returns not_implemented. */}finally{show("Generator belum tersedia (not_implemented).","info");setBusy(false)}}return <><Breadcrumb items={[{label:"Teaching",href:`/workspaces/${slug}/teaching`},{label:config.title}]}/><PageHeader title={config.title} description={config.description}/><form className="surface max-w-4xl p-5 sm:p-7" onSubmit={submit}><div className="grid gap-5 md:grid-cols-2">{config.fields.map(field=><div key={field.name} className={field.type==="textarea"?"md:col-span-2":""}>{field.type==="textarea"?<Textarea label={field.label} required={field.required} value={String(form[field.name])} onChange={e=>setForm({...form,[field.name]:e.target.value})} placeholder={field.placeholder} help={field.help}/>:field.type==="select"?<Select label={field.label} value={String(form[field.name])} onChange={e=>setForm({...form,[field.name]:e.target.value})} options={field.options??[]}/>:field.type==="checkbox"?<label className="flex min-h-11 items-center gap-3 rounded-lg border border-line px-4 text-sm font-medium"><input type="checkbox" checked={Boolean(form[field.name])} onChange={e=>setForm({...form,[field.name]:e.target.checked})} className="h-4 w-4 accent-primary"/>{field.label}</label>:<Input label={field.label} type={field.type??"text"} required={field.required} min={field.min} max={field.max} value={String(form[field.name])} onChange={e=>setForm({...form,[field.name]:field.type==="number"?Number(e.target.value):e.target.value})} placeholder={field.placeholder} help={field.help}/>}</div>)}</div><div className="mt-7 flex items-center justify-between border-t border-line pt-5"><p className="text-xs text-muted">Keluaran akan tersedia setelah layanan generator diaktifkan.</p><Button disabled={busy} type="submit">{busy?"Memproses…":"Generate"}</Button></div></form></>}
