"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";
import { buildMaterialCreatePayload, buildMaterialUpdatePayload, materialTypeOptions } from "@/lib/resource-routes";
import type { Material, Workspace } from "@/lib/types";
import { Button, Input, Select, Textarea } from "@/components/ui";
import { useToast } from "@/components/ui/toast";

export function MaterialForm({workspace,material}:{workspace:Workspace;material?:Material}){
 const router=useRouter();const {show}=useToast();const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [form,setForm]=useState({title:material?.title??"",material_type:material?.material_type??"document",material_date:material?.material_date??"",description:material?.description??"",content_url:material?.content_url??"",content:material?.content??"",tags:(material?.tags??[]).join(", ")});
 const set=(key:string,value:string)=>setForm(current=>({...current,[key]:value}));
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");const body=material?buildMaterialUpdatePayload(form):buildMaterialCreatePayload(workspace.id,form);try{const saved=material?await api<Material>(`/materials/${material.id}`,{method:"PATCH",body:JSON.stringify(body)}):await api<Material>("/materials",{method:"POST",body:JSON.stringify(body)});show(material?"Materi berhasil diperbarui.":"Materi berhasil dibuat.");router.push(`/workspaces/${workspace.slug}/materials/${saved.id}`);router.refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Materi gagal disimpan.")}finally{setBusy(false)}}
 return <form onSubmit={submit} className="surface max-w-4xl p-5 sm:p-7"><div className="grid gap-5 md:grid-cols-2"><div className="md:col-span-2"><Input label="Judul materi" required value={form.title} onChange={e=>set("title",e.target.value)}/></div><Select label="Jenis materi" value={form.material_type} onChange={e=>set("material_type",e.target.value)} options={materialTypeOptions.map(v=>({value:v,label:v[0].toUpperCase()+v.slice(1)}))}/><Input label="Tanggal materi" type="date" value={form.material_date} onChange={e=>set("material_date",e.target.value)}/><div className="md:col-span-2"><Textarea label="Deskripsi" value={form.description} onChange={e=>set("description",e.target.value)}/></div><div className="md:col-span-2"><Input label="URL sumber" type="url" value={form.content_url} onChange={e=>set("content_url",e.target.value)} placeholder="https://…"/></div><div className="md:col-span-2"><Textarea label="Konten / catatan" value={form.content} onChange={e=>set("content",e.target.value)} className="min-h-48"/></div><div className="md:col-span-2"><Input label="Tag" value={form.tags} onChange={e=>set("tags",e.target.value)} help="Pisahkan tag dengan koma."/></div></div>{error&&<p role="alert" className="mt-5 rounded-md border border-[#d8aaa5] bg-[#fff5f3] p-3 text-sm text-[#8d332c]">{error}</p>}<div className="mt-7 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>router.back()}>Batal</Button><Button disabled={busy}>{busy?"Menyimpan…":"Simpan materi"}</Button></div></form>;
}
