"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";
import { buildTemplateCreatePayload, buildTemplateUpdatePayload } from "@/lib/resource-routes";
import type { Template, Workspace } from "@/lib/types";
import { Button, Input, Select, Textarea } from "@/components/ui";
import { useToast } from "@/components/ui/toast";

export function TemplateForm({workspace,template}:{workspace?:Workspace;template?:Template}){const router=useRouter();const {show}=useToast();const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [form,setForm]=useState({name:template?.name??"",category:template?.category??template?.template_type??"lesson",description:template?.description??"",content:String(template?.config_json?.content??""),is_global:template?.workspace_id===null||(!template&&!workspace)});const set=(key:string,value:string|boolean)=>setForm(current=>({...current,[key]:value}));async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");const values={name:form.name,category:form.category,description:form.description,content:form.content};const body=template?buildTemplateUpdatePayload(values):buildTemplateCreatePayload(form.is_global?null:(workspace?.id??null),values);try{const saved=template?await api<Template>(`/templates/${template.id}`,{method:"PATCH",body:JSON.stringify(body)}):await api<Template>("/templates",{method:"POST",body:JSON.stringify(body)});show(template?"Template berhasil diperbarui.":"Template berhasil dibuat.");router.push(workspace?`/workspaces/${workspace.slug}/templates/${saved.id}`:`/templates/${saved.id}`);router.refresh()}catch(reason){const message=reason instanceof Error?reason.message:"Template gagal disimpan.";setError(message);show(message,"info")}finally{setBusy(false)}}return <form onSubmit={submit} className="surface max-w-4xl p-5 sm:p-7"><div className="grid gap-5 md:grid-cols-2"><div className="md:col-span-2"><Input label="Nama template" required value={form.name} onChange={e=>set("name",e.target.value)}/></div><Select label="Kategori" value={form.category} onChange={e=>set("category",e.target.value)} options={["lesson","slides","quiz","assignment","module","general"].map(v=>({value:v,label:v[0].toUpperCase()+v.slice(1)}))}/><label className="flex min-h-11 items-center gap-3 self-end rounded-lg border border-line px-4 text-sm font-medium"><input type="checkbox" checked={form.is_global} onChange={e=>set("is_global",e.target.checked)} className="h-4 w-4 accent-primary"/>Tersedia di library global</label><div className="md:col-span-2"><Textarea label="Deskripsi" value={form.description} onChange={e=>set("description",e.target.value)}/></div><div className="md:col-span-2"><Textarea label="Isi template" required className="min-h-64 font-mono text-sm" value={form.content} onChange={e=>set("content",e.target.value)} placeholder="Struktur, instruksi, atau outline template…"/></div></div>{error&&<p role="alert" className="mt-5 rounded-md border border-[#d8aaa5] bg-[#fff5f3] p-3 text-sm text-[#8d332c]">{error}</p>}<div className="mt-7 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>router.back()}>Batal</Button><Button disabled={busy}>{busy?"Menyimpan…":"Simpan template"}</Button></div></form>}
