"use client";

import { FormEvent,useState } from "react";
import { useRouter,useSearchParams } from "next/navigation";
import { api } from "@/lib/api";
import { safeNextPath } from "@/lib/auth-routes";
import { Button,Input } from "@/components/ui";

export default function LoginForm(){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);const router=useRouter();const params=useSearchParams();async function submit(event:FormEvent){event.preventDefault();setError("");setBusy(true);try{await api("/auth/login",{method:"POST",body:JSON.stringify({email,password})});router.replace(safeNextPath(params.get("next")));router.refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Gagal masuk.")}finally{setBusy(false)}}return <main className="login-shell"><section className="login-story"><div className="flex items-center gap-3"><span className="brand-seal light">D</span><span><strong className="block font-serif text-xl">Derajat</strong><small className="text-[.65rem] uppercase tracking-[.2em] text-[#bcae9a]">Private edition</small></span></div><div className="relative z-10 max-w-2xl"><p className="eyebrow text-[#c5aa82]">Ruang kerja pribadi</p><h1 className="mt-6 font-serif text-5xl leading-[1.05] tracking-[-.035em] text-[#fffaf0] lg:text-6xl">Satu meja kerja.<br/>Seluruh perhatian Anda.</h1><p className="mt-7 max-w-lg text-base leading-8 text-[#d5ccbe]">Tempat pribadi untuk mengelola pekerjaan, pengetahuan, skills, dan rangkaian proses yang ingin Anda jaga.</p></div><div className="relative z-10 flex items-center gap-3 text-xs text-[#a99f91]"><span className="h-px w-12 bg-[#6d604f]"/>Dirancang untuk satu pemilik</div><div aria-hidden className="login-ornament">D</div></section><section className="login-form-side"><div className="w-full max-w-md"><p className="mb-12 flex items-center gap-3 font-serif text-2xl font-semibold text-primary lg:hidden"><span className="brand-seal">D</span>Derajat</p><p className="eyebrow">Akses pribadi</p><h2 className="editorial-title mt-3 text-4xl">Selamat datang kembali</h2><p className="mt-3 text-sm leading-6 text-muted">Masuk untuk melanjutkan ritme kerja Anda.</p><form onSubmit={submit} className="login-card mt-9 space-y-5"><Input label="Email" type="email" autoComplete="email" required value={email} onChange={event=>setEmail(event.target.value)} placeholder="email Anda"/><Input label="Password" type="password" autoComplete="current-password" required value={password} onChange={event=>setPassword(event.target.value)} placeholder="••••••••"/>{error&&<p role="alert" className="error-box">{error}</p>}<Button className="w-full" disabled={busy}>{busy?"Memeriksa…":"Masuk ke ruang saya"}</Button></form><p className="mt-7 text-center text-xs leading-5 text-muted">Ruang ini bersifat privat dan tidak menerima pendaftaran publik.</p></div></section></main>}
