"""initial schema

Revision ID: 1019eabdb289
Revises:
Create Date: 2026-09-07 21:55:55.375647
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1019eabdb289"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("password_version", sa.Integer(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "workspace_type",
            sa.Enum("company", "organization", "personal", name="workspacetype", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_index(op.f("ix_workspaces_slug"), "workspaces", ["slug"], unique=True)
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("workspace_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=True),
        sa.Column("entity_id", sa.String(length=80), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_activity_logs_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_activity_logs_workspace_id_workspaces"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_logs")),
    )
    op.create_index(op.f("ix_activity_logs_action"), "activity_logs", ["action"], unique=False)
    op.create_index(op.f("ix_activity_logs_user_id"), "activity_logs", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_activity_logs_workspace_id"), "activity_logs", ["workspace_id"], unique=False
    )
    op.create_table(
        "modules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("module_type", sa.String(length=80), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_modules_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modules")),
        sa.UniqueConstraint("workspace_id", "slug", name=op.f("uq_modules_workspace_id")),
    )
    op.create_index(op.f("ix_modules_module_type"), "modules", ["module_type"], unique=False)
    op.create_index(op.f("ix_modules_workspace_id"), "modules", ["workspace_id"], unique=False)
    op.create_table(
        "templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("template_type", sa.String(length=80), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_templates_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_templates_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_templates")),
    )
    op.create_index(op.f("ix_templates_category"), "templates", ["category"], unique=False)
    op.create_index(
        op.f("ix_templates_created_by_id"), "templates", ["created_by_id"], unique=False
    )
    op.create_index(op.f("ix_templates_name"), "templates", ["name"], unique=False)
    op.create_index(
        op.f("ix_templates_template_type"), "templates", ["template_type"], unique=False
    )
    op.create_index(op.f("ix_templates_workspace_id"), "templates", ["workspace_id"], unique=False)
    op.create_table(
        "workspace_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "admin", "member", "viewer", name="workspacerole", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_workspace_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workspace_members_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_members")),
        sa.UniqueConstraint(
            "workspace_id", "user_id", name=op.f("uq_workspace_members_workspace_id")
        ),
    )
    op.create_index(
        op.f("ix_workspace_members_user_id"), "workspace_members", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_workspace_members_workspace_id"),
        "workspace_members",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "teaching_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("topic", sa.String(length=240), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("audience", sa.String(length=240), nullable=True),
        sa.Column("difficulty", sa.String(length=40), nullable=True),
        sa.Column("instructor", sa.String(length=200), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("session_type", sa.String(length=80), nullable=True),
        sa.Column("session_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "preparing",
                "ready",
                "scheduled",
                "in_progress",
                "completed",
                "cancelled",
                "archived",
                name="teachingstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_teaching_sessions_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules.id"],
            name=op.f("fk_teaching_sessions_module_id_modules"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_teaching_sessions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teaching_sessions")),
    )
    op.create_index(
        op.f("ix_teaching_sessions_archived_at"), "teaching_sessions", ["archived_at"], unique=False
    )
    op.create_index(
        op.f("ix_teaching_sessions_created_by_id"),
        "teaching_sessions",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teaching_sessions_difficulty"), "teaching_sessions", ["difficulty"], unique=False
    )
    op.create_index(
        op.f("ix_teaching_sessions_module_id"), "teaching_sessions", ["module_id"], unique=False
    )
    op.create_index(
        op.f("ix_teaching_sessions_scheduled_at"),
        "teaching_sessions",
        ["scheduled_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teaching_sessions_session_date"),
        "teaching_sessions",
        ["session_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teaching_sessions_session_type"),
        "teaching_sessions",
        ["session_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teaching_sessions_status"), "teaching_sessions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_teaching_sessions_title"), "teaching_sessions", ["title"], unique=False
    )
    op.create_index(
        op.f("ix_teaching_sessions_topic"), "teaching_sessions", ["topic"], unique=False
    )
    op.create_index(
        op.f("ix_teaching_sessions_workspace_id"),
        "teaching_sessions",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "material_type",
            sa.Enum(
                "document",
                "presentation",
                "video",
                "audio",
                "image",
                "link",
                "spreadsheet",
                "code",
                "archive",
                "other",
                name="materialtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("material_date", sa.Date(), nullable=True),
        sa.Column("content_url", sa.String(length=2048), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("file_path", sa.String(length=2048), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_materials_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules.id"],
            name=op.f("fk_materials_module_id_modules"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["teaching_sessions.id"],
            name=op.f("fk_materials_session_id_teaching_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_materials_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
    )
    op.create_index(
        op.f("ix_materials_created_by_id"), "materials", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_materials_material_date"), "materials", ["material_date"], unique=False
    )
    op.create_index(
        op.f("ix_materials_material_type"), "materials", ["material_type"], unique=False
    )
    op.create_index(op.f("ix_materials_module_id"), "materials", ["module_id"], unique=False)
    op.create_index(op.f("ix_materials_session_id"), "materials", ["session_id"], unique=False)
    op.create_index(op.f("ix_materials_status"), "materials", ["status"], unique=False)
    op.create_index(op.f("ix_materials_title"), "materials", ["title"], unique=False)
    op.create_index(op.f("ix_materials_workspace_id"), "materials", ["workspace_id"], unique=False)
    op.create_table(
        "generated_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=80), nullable=False),
        sa.Column("file_path", sa.String(length=2048), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_generated_files_material_id_materials"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_generated_files_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_files")),
    )
    op.create_index(
        op.f("ix_generated_files_file_type"), "generated_files", ["file_type"], unique=False
    )
    op.create_index(
        op.f("ix_generated_files_material_id"), "generated_files", ["material_id"], unique=False
    )
    op.create_index(
        op.f("ix_generated_files_workspace_id"), "generated_files", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generated_files_workspace_id"), table_name="generated_files")
    op.drop_index(op.f("ix_generated_files_material_id"), table_name="generated_files")
    op.drop_index(op.f("ix_generated_files_file_type"), table_name="generated_files")
    op.drop_table("generated_files")
    op.drop_index(op.f("ix_materials_workspace_id"), table_name="materials")
    op.drop_index(op.f("ix_materials_title"), table_name="materials")
    op.drop_index(op.f("ix_materials_status"), table_name="materials")
    op.drop_index(op.f("ix_materials_session_id"), table_name="materials")
    op.drop_index(op.f("ix_materials_module_id"), table_name="materials")
    op.drop_index(op.f("ix_materials_material_type"), table_name="materials")
    op.drop_index(op.f("ix_materials_material_date"), table_name="materials")
    op.drop_index(op.f("ix_materials_created_by_id"), table_name="materials")
    op.drop_table("materials")
    op.drop_index(op.f("ix_teaching_sessions_workspace_id"), table_name="teaching_sessions")
    op.drop_index(op.f("ix_teaching_sessions_topic"), table_name="teaching_sessions")
    op.drop_index(op.f("ix_teaching_sessions_title"), table_name="teaching_sessions")
    op.drop_index(op.f("ix_teaching_sessions_status"), table_name="teaching_sessions")
    op.drop_index(op.f("ix_teaching_sessions_session_type"), table_name="teaching_sessions")
    op.drop_index(op.f("ix_teaching_sessions_session_date"), table_name="teaching_sessions")
    op.drop_index(op.f("ix_teaching_sessions_scheduled_at"), table_name="teaching_sessions")
    op.drop_index(op.f("ix_teaching_sessions_module_id"), table_name="teaching_sessions")
    op.drop_index(op.f("ix_teaching_sessions_difficulty"), table_name="teaching_sessions")
    op.drop_index(op.f("ix_teaching_sessions_created_by_id"), table_name="teaching_sessions")
    op.drop_index(op.f("ix_teaching_sessions_archived_at"), table_name="teaching_sessions")
    op.drop_table("teaching_sessions")
    op.drop_index(op.f("ix_workspace_members_workspace_id"), table_name="workspace_members")
    op.drop_index(op.f("ix_workspace_members_user_id"), table_name="workspace_members")
    op.drop_table("workspace_members")
    op.drop_index(op.f("ix_templates_workspace_id"), table_name="templates")
    op.drop_index(op.f("ix_templates_template_type"), table_name="templates")
    op.drop_index(op.f("ix_templates_name"), table_name="templates")
    op.drop_index(op.f("ix_templates_created_by_id"), table_name="templates")
    op.drop_index(op.f("ix_templates_category"), table_name="templates")
    op.drop_table("templates")
    op.drop_index(op.f("ix_modules_workspace_id"), table_name="modules")
    op.drop_index(op.f("ix_modules_module_type"), table_name="modules")
    op.drop_table("modules")
    op.drop_index(op.f("ix_activity_logs_workspace_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_user_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_action"), table_name="activity_logs")
    op.drop_table("activity_logs")
    op.drop_index(op.f("ix_workspaces_slug"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
