"""add skills and orchestrations

Revision ID: e188bd7fe19b
Revises: 1019eabdb289
Create Date: 2026-09-08 03:21:10.575291
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e188bd7fe19b"
down_revision: str | None = "1019eabdb289"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_state",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_application_state")),
    )
    op.create_table(
        "orchestrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_orchestrations_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_orchestrations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orchestrations")),
    )
    op.create_index(
        op.f("ix_orchestrations_created_by_id"), "orchestrations", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_orchestrations_workspace_id"), "orchestrations", ["workspace_id"], unique=False
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_skills_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_skills_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
        sa.UniqueConstraint("workspace_id", "slug", name=op.f("uq_skills_workspace_id")),
    )
    op.create_index(op.f("ix_skills_created_by_id"), "skills", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_skills_workspace_id"), "skills", ["workspace_id"], unique=False)
    op.create_table(
        "orchestration_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("orchestration_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["orchestration_id"],
            ["orchestrations.id"],
            name=op.f("fk_orchestration_steps_orchestration_id_orchestrations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_orchestration_steps_skill_id_skills"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orchestration_steps")),
        sa.UniqueConstraint(
            "orchestration_id", "position", name=op.f("uq_orchestration_steps_orchestration_id")
        ),
        sa.UniqueConstraint(
            "orchestration_id", "skill_id", name=op.f("uq_orchestration_steps_orchestration_id")
        ),
    )
    op.create_index(
        op.f("ix_orchestration_steps_orchestration_id"),
        "orchestration_steps",
        ["orchestration_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_orchestration_steps_skill_id"), "orchestration_steps", ["skill_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orchestration_steps_skill_id"), table_name="orchestration_steps")
    op.drop_index(op.f("ix_orchestration_steps_orchestration_id"), table_name="orchestration_steps")
    op.drop_table("orchestration_steps")
    op.drop_index(op.f("ix_skills_workspace_id"), table_name="skills")
    op.drop_index(op.f("ix_skills_created_by_id"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(op.f("ix_orchestrations_workspace_id"), table_name="orchestrations")
    op.drop_index(op.f("ix_orchestrations_created_by_id"), table_name="orchestrations")
    op.drop_table("orchestrations")
    op.drop_table("application_state")
    # ### end Alembic commands ###
